import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./styles/globals.scss";

export const metadata = {
  title: "MY PROTFOLIO",
  description: "Generated by create RONY",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
